---
title: Bowled Over
logo:
description: A blog all about creating healthy, vegetarian-ish lunch bowls for the week and more.
twitter:
favicon:
url:
gtm:
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: 'recipes'
  values:
    layout: recipe
    permalink: /recipe/:title/
collections:
  recipes:
    output: true
  pages:
    output: true
