---
title: Bowled Over
description: A blog all about creating healthy, vegetarian-ish lunch bowls for the week.
meta_img:
twitter:
favicon:
url:
gtm:
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: 'recipe'
  values:
    permalink: /:title/
    layout: recipe
collections:
  recipes:
    output: true
